data:
  input_file: "predictive_maintenance.csv"
  target_column: "Target"
  drop_columns:
    - "Product ID"
    - "UDI"

model:
  test_size: 0.3
  random_state: 42
  stratify: True
  imputer_strategy: "constant"

output:
  model_file: "logistic_regression_model.pkl"
