data:
  input_file: "predictive_maintenance.csv"
  target_column: "Target"
  drop_columns:
    - "Product ID"
    - "UDI"
    - "Failure Type"

model:
  imputer_strategy: "constant"

output:
  model_file: "logistic_regression_model.pkl"
